import Foundation

/// Overrides the value a zero-argument method returns.
///
/// Applied by replacing the method's implementation at runtime (`method_setImplementation`),
/// the way Flex-style patches work — no jailbreak, and the change rides along in a dylib
/// that AppSigner injects and re-signs. Best suited to getters (`isPremium`, `count`, …).
public struct MethodPatch: Equatable, Codable, Identifiable {
    public enum ReturnValue: Equatable, Codable {
        case boolean(Bool)
        case integer(Int)
        case double(Double)
        case string(String)
        case null
    }
    public var id = UUID()
    public let className: String
    public let selector: String
    public let value: ReturnValue

    public init(className: String, selector: String, value: ReturnValue) {
        self.className = className; self.selector = selector; self.value = value
    }

    public var summary: String {
        let v: String
        switch value {
        case .boolean(let b): v = b ? "YES" : "NO"
        case .integer(let i): v = String(i)
        case .double(let d): v = String(d)
        case .string(let s): v = "\"\(s)\""
        case .null: v = "nil"
        }
        return "\(className).\(selector) → \(v)"
    }
}

/// Generates the Objective-C source for a patch dylib from a list of `MethodPatch`.
public enum PatchGenerator {
    public static func source(for patches: [MethodPatch]) -> String {
        var body = ""
        for patch in patches {
            let cls = escape(patch.className)
            body += """
                    patchMethod("\(cls)", @selector(\(patch.selector)), (IMP)imp_implementationWithBlock(\(block(for: patch.value))));

                """
        }

        return """
        // Generated by AppSigner — overrides method return values at runtime by swizzling.
        #import <Foundation/Foundation.h>
        #import <objc/runtime.h>
        #import <objc/message.h>

        static void patchMethod(const char *className, SEL selector, IMP newImp) {
            Class cls = objc_getClass(className);
            if (!cls) { NSLog(@"[AppSignerPatches] class %s not found", className); return; }
            Method instanceMethod = class_getInstanceMethod(cls, selector);
            if (instanceMethod) { method_setImplementation(instanceMethod, newImp); return; }
            Method classMethod = class_getClassMethod(cls, selector);
            if (classMethod) { method_setImplementation(classMethod, newImp); return; }
            NSLog(@"[AppSignerPatches] %s does not respond to %s", className, sel_getName(selector));
        }

        __attribute__((constructor))
        static void applyAppSignerPatches(void) {
        \(body)}
        """
    }

    /// The block that returns the patched value. Its first parameter is the receiver.
    private static func block(for value: MethodPatch.ReturnValue) -> String {
        switch value {
        case .boolean(let b): return "^BOOL(__unsafe_unretained id _self){ return \(b ? "YES" : "NO"); }"
        case .integer(let i): return "^NSInteger(__unsafe_unretained id _self){ return \(i); }"
        case .double(let d):  return "^double(__unsafe_unretained id _self){ return \(d); }"
        case .string(let s):  return "^id(__unsafe_unretained id _self){ return @\"\(escape(s))\"; }"
        case .null:           return "^id(__unsafe_unretained id _self){ return nil; }"
        }
    }

    private static func escape(_ text: String) -> String {
        text.replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
    }
}
